// Example for sentiments
const examples = [
    { "text": "They are going to plant a tree.", "label": "positive" },
    { "text": "Bill will join swimming classes this summer.", "label": "positive" },
    { "text": "My sister brought home a very cute puppy.", "label": "positive" },
    { "text": "The work is due today.", "label": "positive" },
    { "text": "I have a plan.", "label": "positive" },
    { "text": "I have mashed potatoes for dinner.", "label": "positive" },
    { "text": "We took many photos at the party.", "label": "positive" },
    { "text": "The school reopens after the summer holidays.", "label": "positive" },
    { "text": "Riya is taller than her sister.", "label": "positive" },
    { "text": "The baby crawled all morning.", "label": "positive" },
    { "text": "I love this car.", "label": "positive" },
    { "text": "He is my best friend.", "label": "positive" },
    { "text": "Wow... Loved this place.", "label": "positive" },
    { "text": "Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.", "label": "positive" },
    { "text": "The selection on the menu was great and so were the prices.", "label": "positive" },
    { "text": "This view is horrible.", "label": "negative" },
    { "text": "I feel tired this morning.", "label": "negative" },
    { "text": "I am not looking forward to the concert.", "label": "negative" },
    { "text": "He is my enemy.", "label": "negative" },
    { "text": "I do not love you anymore.", "label": "negative" },
    { "text": "I will not go to school today.", "label": "negative" },
    { "text": "This old man was not actually right.", "label": "negative" },
    { "text": "There was no peach orchard on site of this building.", "label": "negative" },
    { "text": "He does not catches the bus every morning.", "label": "negative" },
    { "text": "Alex isn’t telling the truth.", "label": "negative" },
    { "text": "He couldn’t get unhealthy food.", "label": "negative" },
    { "text": "The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer. ", "label": "negative" },
    { "text": "The Burrittos Blah!", "label": "negative" },
    { "text": "Not tasty and the texture was just nasty.", "label": "negative" },
    { "text": "Crust is not good.", "label": "negative" },
    { "text": "There is a book on the desk.", "label": "neutral" },
    { "text": "Childhood is the time to play.", "label": "neutral" },
    { "text": "The order came 5 days early", "label": "positive" },
    { "text": "The item exceeded my expectations", "label": "positive" },
    { "text": "I ordered more for my friends", "label": "positive" },
    { "text": "I would buy this again", "label": "positive" },
    { "text": "I would recommend this to others", "label": "positive" },
    { "text": "The package was damaged", "label": "negative" },
    { "text": "The order is 5 days late", "label": "negative" },
    { "text": "The order was incorrect", "label": "negative" },
    { "text": "I want to return my item", "label": "negative" },
    { "text": "The item\'s material feels low quality", "label": "negative" },
    { "text": "The product was okay", "label": "neutral" },
    { "text": "I received five items in total", "label": "neutral" },
    { "text": "I bought it from the website", "label": "neutral" },
    { "text": "I used the product this morning", "label": "neutral" },
    { "text": "The product arrived yesterday", "label": "neutral" }
]

module.exports = examples;